require('mason').setup()
require('mason-lspconfig').setup()


require('lsp.keymapping')
require('lsp.pyright')
require('lsp.tsserver')
require('lsp.json')
require('lsp.css')
require('lsp.tailwindcss')
require('lsp.html')
require('lsp.lua-lsp')
require('lsp.bashls')
require('lsp.ltex')
require('lsp.r-lsp')
require('lsp.rust')
require('lsp.clangd')
require('lsp.zls')
require('lsp.java')

