tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "bash"
brew "python@3.9", link: false
brew "coreutils"
brew "libssh2"
brew "openldap"
brew "curl"
brew "deno"
brew "unbound", link: false
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "gcc", link: false
brew "ghostscript", link: false
brew "git"
brew "grep"
brew "krb5"
brew "libcroco"
brew "pango"
brew "librsvg"
brew "lua"
brew "luajit"
brew "tree-sitter"
brew "neovim"
brew "node", link: false
brew "perl"
brew "postgresql"
brew "python@3.8"
brew "ruby"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "youtube-dl"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
