syntax on
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set number
set autoindent
set backspace=indent,eol,start
set encoding=UTF-8
set nowrap
set sidescroll=1
set termguicolors

" map F1 to escape
nmap <F1> <Esc>
imap <F1> <Esc>


call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'rose-pine/vim'
Plug 'embark-theme/vim', { 'as': 'embark', 'branch': 'main' }
call plug#end()

nmap ff :FZF<CR>
