# profile name
env TERM_PROFILE=evil

font_family           FreeMono
foreground            #D94F4F
background            #000000
selection_foreground  #000000
selection_background  #D94F4F
cursor                #D94F4F
cursor_text_color     #000000


# black
color0  #000000
color8  #000000

# red
color1  #D94F4F
color9  #D94F4F

# green
color2  #D94F4F
color10 #D94F4F

# yellow
color3  #D94F4F
color11 #D94F4F

# blue
color4  #D94F4F
color12 #D94F4F

# magenta
color5  #D94F4F
color13 #D94F4F

# cyan
color6  #D94F4F
color14 #D94F4F

# white
color7  #D94F4F
color15 #D94F4F


background_blur 0
background_opacity 0.80
dynamic_background_opacity yes

# active_border_color   #00ff00
# inactive_border_color #cccccc
